// +build ignore

//go:generate go run SwaggerGen.go

package main

import (
	"fmt"
	"io/ioutil"
	"log"
	"os"
	"text/template"
	"time"
)

func main() {
	files, err := ioutil.ReadDir("./")
	if err != nil {
		log.Fatal(err)
	}

	for _, f := range files {
		fmt.Println(f.Name())
	}

	swaggerBytes, err := ioutil.ReadFile("Jobs.swagger.json")
	if err != nil {
		log.Fatalln(err.Error())
	}

	f, err := os.Create("Swagger.go")
	if err != nil {
		log.Fatalln(err.Error())
	}

	defer f.Close()

	packageTemplate.Execute(f, struct {
		Timestamp time.Time
		JSON      []byte
	}{
		Timestamp: time.Now(),
		JSON:      swaggerBytes,
	})
}

var packageTemplate = template.Must(template.New("").Parse(`
// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots at
// {{ .Timestamp }}
package swaggerhandler

var SwaggerJSON = []byte{
{{range .JSON -}}
	{{printf "%q" . }},

{{- end }}
}
`))
